version: '3'
services:
  github-test-backend:
    container_name: commits-server-api
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
