version: '3'
services:
  github-test-backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
  ultrahook-github:
    depends_on:
      - github-test-backend
    build:
      context: .
      dockerfile: Dockerfile.ultrahook
    environment:
      API_KEY: ${ULTRAHOOK_API_KEY}
      SUBDOMAIN: github
      DESTINATION: ${ULTRAHOOK_GITHUB_ENDPOINT_TARGET}
